import type { Disciple, Language, Audience } from './types';

export const DISCIPLES: Disciple[] = [
  { id: "peter", name: "Peter" },
  { id: "andrew", name: "Andrew" },
  { id: "james_son_of_zebedee", name: "James (Son of Zebedee)" },
  { id: "john", name: "John" },
  { id: "philip", name: "Philip" },
  { id: "bartholomew", name: "Bartholomew (Nathanael)" },
  { id: "thomas", name: "Thomas" },
  { id: "matthew", name: "Matthew" },
  { id: "james_son_of_alphaeus", name: "James (Son of Alphaeus)" },
  { id: "thaddeus", name: "Thaddeus (Jude)" },
  { id: "simon_the_zealot", name: "Simon the Zealot" },
  { id: "judas_iscariot", name: "Judas Iscariot" },
  { id: "mary_magdalene", name: "Mary Magdalene" },
  { id: "paul", name: "Paul (Saul of Tarsus)" },
];

export const LANGUAGES: Language[] = [
    { code: "ar", name: "العربية (Arabic)" },
    { code: "bn", name: "বাংলা (Bengali)" },
    { code: "zh", name: "中文 (Chinese)" },
    { code: "cs", name: "Čeština (Czech)" },
    { code: "da", name: "Dansk (Danish)" },
    { code: "nl", name: "Nederlands (Dutch)" },
    { code: "en", name: "English" },
    { code: "tl", name: "Tagalog (Filipino)" },
    { code: "fi", name: "Suomi (Finnish)" },
    { code: "fr", name: "Français" },
    { code: "de", name: "Deutsch" },
    { code: "el", name: "Ελληνικά (Greek)" },
    { code: "he", name: "עברית (Hebrew)" },
    { code: "hi", name: "हिन्दी (Hindi)" },
    { code: "hu", name: "Magyar (Hungarian)" },
    { code: "id", name: "Bahasa Indonesia" },
    { code: "it", name: "Italiano" },
    { code: "ja", name: "日本語 (Japanese)" },
    { code: "rw", name: "Kinyarwanda" },
    { code: "ko", name: "한국어 (Korean)" },
    { code: "ms", name: "Bahasa Melayu" },
    { code: "no", name: "Norsk (Norwegian)" },
    { code: "pl", name: "Polski (Polish)" },
    { code: "pt", name: "Português" },
    { code: "ro", name: "Română (Romanian)" },
    { code: "ru", name: "Русский (Russian)" },
    { code: "es", name: "Español" },
    { code: "sw", name: "Kiswahili" },
    { code: "sv", name: "Svenska (Swedish)" },
    { code: "th", name: "ภาษาไทย (Thai)" },
    { code: "tr", name: "Türkçe (Turkish)" },
    { code: "ur", name: "اردو (Urdu)" },
    { code: "vi", name: "Tiếng Việt (Vietnamese)" },
];

export const AUDIENCES: Audience[] = [
  { id: "youth", name: "Youth" },
  { id: "young_adult", name: "Young Adult" },
  { id: "adult", name: "Adult" },
];
